---
title: "Test"
author: "Zijie Huang"
date: "2020/12/11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("tidyquant","tidyverse","curl","httr")
```

```{r}
#Get stock value in exchange
#nyse <- tq_exchange("NYSE")
#amex <- tq_exchange("AMEX")
#nasdaq <- tq_exchange("NASDAQ")

#load data
load("full_exchange.RData")
```

```{r}
#Combine exchange
#full_exchange <- rbind(nyse,nasdaq,amex)

#Delete replicates
#full_exchange <- full_exchange %>% distinct()

#Save file
#save(full_exchange,file = "full_exchange.RData")

#Get price
full_stock <- tq_get(x = full_exchange$symbol[1], from = "2020-07-01", to = "2020-12-01", get = "stock.prices")

full_exchange

rows <- nrow(full_exchange)

for(i in 2:rows){
    print(i)
    single_stock <- tq_get(x = full_exchange$symbol[i], from = "2020-07-01", to = "2020-12-01", get = "stock.prices")
  
    full_stock <- rbind(full_stock, single_stock)
}

#Join two table
full_stock <- left_join(full_stock,full_exchange[,c(1,2,6)],by = "symbol")

#Save file
save(full_stock,file = "full_stock.RData")
```

```{r}
nyse_stock
ggplot(data = nyse_stock, aes(x = date, y = adjusted)) +
  geom_line()
```